import * as React from "react";
import styles from './index.module.css';

function PopUp(props) {

    return(
        <div class={styles.hover_bkgr_fricc}>
	<span class={styles.helper}></span>
	<div>
		<div class={styles.popupCloseButton}>&times;</div>
        <p>
            <br />1. Introducción<br /><br /><br />
            <br />1. Estos Términos de servicio se aplican al uso del Servicio de MAKNAD (como se define a continuación). Al utilizar el Servicio, acepta los Términos de servicio y firma un acuerdo con MAKNAD (en adelante, el "Acuerdo"). Si no desea aceptar los Términos de servicio, no puede utilizar el Servicio.
            <br />2. MAKNAD es una Asociación estudiantil “Asociación Junior Empresa” (en adelante TRAK PHYSIO)  y existente bajo las leyes de España, con domicilio social en Leandro Aguirretxe Plazatxoa 1, Irún, y activa en el sitio web de www.trak.es (en adelante “ Sitio web").
            <br />3. Le recomendamos que lea atentamente estos Términos de servicio para que conozca sus derechos y responsabilidades al utilizar el Servicio de TRAK PHYSIO. Las preguntas sobre los Términos de servicio deben enviarse a info@trak.es .
            <br /><br /><br />2 - General<br /><br /><br />
            <br />1. Estos Términos de servicio se aplican, con exclusión de sus términos y condiciones, a todos los acuerdos entre usted y TRAK PHYSIO y a todo uso que se haga del Servicio a través de su Cuenta.
            <br />2. TRAK PHYSIO se reserva el derecho de modificar o complementar estos Términos de servicio en cualquier momento mediante la publicación de un conjunto actualizado de términos y condiciones en el sitio web. Los Términos de servicio modificados o complementados se le comunicarán por correo electrónico a la dirección registrada en su Cuenta y mediante un aviso en el sitio web antes de la fecha en la que dichos términos y condiciones actualizados entren en vigor. Si continúa utilizando el Servicio después de esa fecha, acepta irrevocablemente los Términos de servicio modificados o complementados. Si no está de acuerdo con los Términos de servicio modificados o complementados, su única opción es rescindir el Acuerdo de conformidad con el artículo 9.
            <br />3. Cualquier adición y / o desviación de estos Términos de servicio, ya sea de forma temporal o permanente, sólo son válidas cuando TRAK PHYSIO lo confirma por escrito, actuando por un funcionario autorizado, como un director o gerente senior.
            <br /><br /><br />3 - Servicio y disponibilidad<br /><br /><br />
            <br />1. TRAK PHYSIO ha desarrollado una plataforma, denominada Trak, que permite a los profesionales sanitarios gestionar programas de ejercicios en el hogar para sus pacientes, incluida la gestión del cumplimiento del programa de ejercicios por parte de los pacientes y el feedback en tiempo real mediante el algoritmo de Inteligencia Artificial (en adelante “ Plataforma"). La Plataforma es accesible por TRAK PHYSIO a través de la web www.trak.es (en adelante, el "Servicio"). Para obtener acceso al Servicio, debe tener una cuenta registrada (en adelante, "Cuenta").
            <br />2. Sujeto a su cumplimiento total y continuo de todas las obligaciones de conformidad con estos Términos de servicio, TRAK PHYSIO le otorga un derecho limitado, personal, revocable, no exclusivo, no sublicenciable e intransferible para usar el Servicio, incluido el Plataforma para los fines anteriores (pero no adicionales o de otro tipo).
            <br />3. TRAK PHYSIO hará todos los esfuerzos razonables para proporcionar el Servicio con el debido cuidado. Acepta que el Servicio, incluida la Plataforma, solo contiene las funcionalidades y otras características descritas en la documentación actual tal como se establece en el momento de su uso ("tal cual" y "según esté disponible"). Todos y cada uno de los usos del Servicio es bajo su propio riesgo y responsabilidad. TRAK PHYSIO no garantiza que la prestación del Servicio sea ininterrumpida o libre de errores y TRAK PHYSIO no acepta responsabilidad por ninguna parte de la infraestructura de prestación del servicio (incluido, entre otros, Internet) que esté fuera de su control razonable.
            <br />4. TRAK PHYSIO tiene derecho en todo momento, sin que de ninguna manera se vuelva responsable ante usted:
            <br />- realizar modificaciones técnicas y de procedimiento y / o mejoras en la Plataforma y / o el Servicio; y
            <br />- interrumpir o limitar temporalmente el Servicio o su Cuenta si, en su opinión, esto es necesario, por ejemplo, para fines de mantenimiento preventivo, correctivo o adaptativo. TRAK PHYSIO le notificará sobre la indisponibilidad temporal o el uso restringido del Servicio en la medida y tan pronto como sea razonablemente posible.
            <br /><br /><br />4 - Cuenta<br /><br /><br />
            <br />1. Para utilizar el Servicio, debe crear una Cuenta siguiendo el proceso de registro en el Sitio web.
            <br />2. Tras el registro de la Cuenta, establecerá su nombre de usuario y contraseña única (juntos "identificadores") para obtener acceso a la Cuenta. Usted es responsable de mantener en secreto los identificadores. Tan pronto como sepa o tenga motivos para sospechar que los identificadores ya no son secretos, o que se está abusando de la Cuenta, debe notificar a TRAK PHYSIO de inmediato y tomar todas las medidas necesarias para evitar el acceso no autorizado, incluido el cambio de identificadores relevantes y tomar otras medidas de seguridad como recomendado por su proveedor de infraestructura.
            <br />3. No se le permite:
            <br />- proporcionar información durante el registro que no sea precisa, completa y actualizada;
            <br />- crear más de una cuenta;
            <br />- crear una cuenta para otra persona física o jurídica;
            <br />- compartir una Cuenta o de cualquier otra forma proporcionar acceso a la Cuenta a otra persona física o jurídica; o
            <br />- cree una cuenta si es menor de 18 años.
            <br />4. En el caso de un paciente, puede descargar del Servicio sus programas de ejercicio y los detalles de su cuenta estrictamente para su uso personal, no comercial, siempre que mantenga intactos todos los avisos de derechos de autor y otros avisos de propiedad.
            <br />5. En el caso del proveedor de atención médica, puede descargar del Servicio el programa de ejercicios de su paciente y el historial de cumplimiento estrictamente con el propósito de mantener los registros de su paciente y no debe vender, redistribuir o usar para ningún otro propósito. No puede utilizar ningún medio para exportar y / o descargar el programa de ejercicios de su paciente y el historial de cumplimiento, excepto los medios expresamente proporcionados para tal fin por TRAK PHYSIO.
            <br /><br /><br />5 - Obligaciones<br /><br /><br />
            <br />1. Al usar el Servicio, no se le permite realizar los actos que se enumeran a continuación:
            <br />- hacer que el contenido (incluida toda la información, los datos o el material, como los programas de ejercicios (en adelante, el "Contenido")) estén disponibles que, a discreción de TRAK PHYSIO, sea ​​discriminatorio o se considere dañino, ofensivo o inapropiado;
            <br /> - tratar datos personales, de forma distinta a la de la legislación aplicable;
            <br />- Poner a disposición Contenido que contenga virus, caballos de Troya, gusanos, bots u otro software que pueda causar cualquier interferencia, pérdida o daño a la Plataforma o cualquier dato o inutilizarlo o inaccesible o eliminarlo, o que pueda apropiarse de él o que sea destinado a eludir las medidas técnicas de protección del Servicio, la Plataforma y / o los sistemas informáticos de TRAK PHYSIO;
            <br />- Poner a disposición Contenido dirigido a personas (incluidos pacientes) menores de 18 años, a menos que exista el consentimiento previo de los padres o tutores de dichas personas;
            <br /> - Hacer o transmitir cualquier material o Contenido no deseado o no solicitado (spam);
            <br />- Poner a disposición Contenido que pueda perjudicar los intereses y la reputación de TRAK PHYSIO.
            <br />2. TRAK PHYSIO se reserva el derecho, sin previo aviso, de abreviar, alterar, rechazar y / o eliminar cualquier Contenido a su absoluta discreción y responsabilidad.
            <br />3. En el caso del proveedor de atención médica, no puede crear programas de ejercicios en el hogar para más pacientes de los acordados para su Cuenta. La limitación aplicable sobre el número de pacientes se mencionará en el sitio web antes de la celebración del Acuerdo.
            <br />4. Las infracciones de este artículo 5 pueden dar lugar a la suspensión o terminación del derecho a utilizar el Servicio y TRAK PHYSIO podrá, en cualquier caso, reclamar daños y perjuicios por cualquier incumplimiento de este artículo 5.
            <br /><br /><br />6 - Privacidad<br /><br /><br />
            <br />1. Si es un paciente, al utilizar el Servicio, tanto usted como su proveedor de atención médica pueden proporcionar a TRAK PHYSIO información de contacto e información médica sobre usted. Si usted es un proveedor de atención médica, al utilizar el Servicio, tanto usted como sus pacientes pueden proporcionar a TRAK PHYSIO información de contacto y otra información sobre usted. TRAK PHYSIO utiliza estos datos únicamente con fines administrativos y de investigación relacionados con la prestación de un Servicio estable y confiable a pacientes y proveedores de atención médica y observará la Ley de Protección de Datos y las leyes de privacidad australianas en relación con el suministro de esta información y cualquier regla relevante y, cuando corresponda , códigos de práctica relacionados con los registros médicos según lo exige la ley. Nuestra Política de privacidad establecida en el sitio web se aplicará a usted y a su uso del Servicio. Usted da su consentimiento para el uso,divulgación y conservación de su información de acuerdo con nuestra Política de privacidad.
            <br />2. Si usted es un proveedor de atención médica, acepta y acepta que es responsable del
            <br />cumplimiento de toda la legislación de privacidad aplicable como proveedor de atención médica al paciente y
            <br />ningún acto u omisión de TRAK PHYSIO lo eximirá de sus obligaciones. Según la ley de protección de datos , TRAK PHYSIO actúa como encargado de tratamiento solo de conformidad con la Ley de protección de datos y usted sigue siendo el controlador de datos con respecto a todos los datos procesados ​​mediante el Servicio.
            <br />TRAK PHYSIO solo procesará datos personales en la medida en que sea necesario para la ejecución del acuerdo con el proveedor de atención médica y sus instrucciones por escrito, a menos que TRAK PHYSIO esté obligado por ley a procesar datos personales fuera de este alcance o si el paciente ha dado su consentimiento para dicho procesamiento a TRAK PHYSIO. Con respecto al procesamiento de datos personales a que se refiere esta disposición, TRAK PHYSIO y el proveedor de atención médica pueden celebrar un acuerdo de procesamiento . En determinadas circunstancias, TRAK PHYSIO también puede procesar sus datos personales para sus propios fines, según se especifica en la Política de privacidad establecida en este sitio web. De conformidad con la legislación de privacidad mencionada anteriormente, es posible que tenga obligaciones de acceso hacia sus pacientes, como la obligación de proporcionar información y permitir la inspección, corrección, retención y eliminación de los datos personales del paciente. Usted es total y exclusivamente responsable de garantizar el cumplimiento de estas obligaciones; incluida la realización de copias de seguridad periódicas del paciente información en la forma requerida por la legislación, las normas y el código de práctica pertinentes que se aplican a usted como proveedor de atención médica. TRAK PHYSIO proporcionará su asistencia razonable al proveedor de atención médica para cumplir con las solicitudes de los pacientes con respecto a sus datos personales. En la medida en que sea necesario el consentimiento del paciente, usted será responsable de obtener dicho consentimiento.
            <br />
            <br />
            <br />3. TRAK PHYSIO hará todo lo posible para mantener los datos personales recibidos del proveedor de atención médica en estricta confidencialidad y para implementar las medidas técnicas y organizativas adecuadas para proteger los datos personales contra cualquier forma de procesamiento ilegal y / o no autorizado de datos personales. TRAK PHYSIO proporcionará su asistencia razonable al proveedor de atención médica, para que el proveedor de atención médica cumpla con sus obligaciones con respecto a la evaluación de la efectividad de las medidas de seguridad, la seguridad de los datos personales y las notificaciones de incumplimiento.
            <br />
            <br /><br /><br />7 - Derechos de propiedad intelectual<br /><br /><br />
            <br />1. Los derechos de propiedad intelectual, incluidos, entre otros, los derechos de autor, derechos de base de datos y derechos de nombres comerciales (en adelante, "derechos de propiedad intelectual"), en relación con el Servicio, incluida la Plataforma, son propiedad de TRAK PHYSIO. Nada en los Términos de servicio tiene la intención de implicar una transferencia de derechos de propiedad intelectual a usted.
            <br />2. Conserva todos los derechos de propiedad intelectual sobre el Contenido que proporciona a través del Servicio. Al poner a disposición o cargar Contenido en el Servicio, automáticamente otorga a TRAK PHYSIO un derecho gratuito, mundial, irrevocable, sublicenciable y transferible para usar este Contenido en la medida en que esté relacionado con la prestación del Servicio.
            <br />3. Salvo en la medida en que lo permita la ley obligatoria, no podrá reproducir ni descompilar la Plataforma ni aplicarle ingeniería inversa. Además, no se permite la eliminación y / o elusión de medidas de seguridad o limitaciones técnicas (de uso) del Servicio y / o la Plataforma.
            <br /><br /><br />8 - Plazo y rescisión<br /><br /><br />
            <br />1. Usted acepta que su uso del Servicio es por un período de tiempo definido, ya sea un mes o un año (período inicial). Una vez transcurrido el período inicial, su derecho de acceso para utilizar el Servicio se renovará automáticamente por el mismo período de tiempo (mes o año), sujeto a estos Términos y Condiciones.
            <br />2. Puede cancelar su Cuenta y acceder al Servicio en cualquier momento dentro de la configuración de su Cuenta. Si usted es un proveedor de atención médica y existen programas de ejercicios que se extienden más allá del período de suscripción actual, debe editar manualmente los programas de estos pacientes para que finalicen dentro del período de suscripción actual antes de poder cancelar su Cuenta y acceder para usar el Servicio. No obstante lo anterior, si usted es un paciente, su acceso a la Plataforma cesará cuando su proveedor de atención médica cese el acceso al Servicio.
            <br />3. Si usted es un proveedor de atención médica y termina 10 días o más antes del final del período de suscripción actual, su cancelación entrará en vigencia al final del período de suscripción actual y no se le cobrará por el siguiente período de suscripción. Si cancela menos de 10 días antes del final del período de suscripción actual, su cancelación entrará en vigencia al final del siguiente período de suscripción y las tarifas continuarán adeudadas y pagaderas durante el próximo período de suscripción.
            <br />4. TRAK PHYSIO tiene derecho a interrumpir inmediatamente o suspender (temporalmente) su Servicio o rescindir el Acuerdo, sin perjuicio de los demás derechos y recursos de TRAK PHYSIO, incluido su derecho a reclamar daños: - si incumple sus obligaciones en virtud del Acuerdo y / o Términos de servicio; o - en caso de que quiebre o se le conceda una suspensión de pagos, así como en caso de que su negocio sea cerrado o liquidado.
            <br />5. En caso de que se cancele la Cuenta, no recibirá ningún reembolso como resultado de la cancelación.
            <br />6. Tras la terminación del Acuerdo, si usted es un proveedor de atención médica, TRAK PHYSIO mantendrá todo el Contenido a su disposición durante un período de 30 días después de la finalización del Acuerdo. Podrá utilizar el Servicio durante este mes en la medida en que sea necesario para la exportación de su Contenido. No puede agregar ningún Contenido. Después de este periodo, TRAK PHYSIO hará que su Cuenta sea inaccesible para usted. TRAK PHYSIO no estará obligado a proporcionarle ningún Contenido u otra información ni a convertir o exportar dicha información. Esta cláusula no se aplica cuando su acceso al Servicio se cancela como resultado de un incumplimiento de sus obligaciones en virtud de estos Términos de servicio.
            <br />7. Después del cese de un proveedor de atención médica, por cualquier motivo, los pacientes no podrán acceder a ningún programa de ejercicio asignado por ese proveedor de atención médica. TRAK PHYSIO seguirá teniendo derecho a utilizar el Contenido que proporcionó durante el Acuerdo, tal como se establece en el artículo 8, en la medida en que haya compartido el Contenido con otros clientes de TRAK PHYSIO.
            <br /><br /><br />9 - Responsabilidad<br /><br /><br />
            <br />1. En la máxima medida permitida por la ley, la responsabilidad de TRAK PHYSIO bajo cualquier garantía, condición o garantía (incluyendo, sin limitación, cualquier garantía, condición o garantía de comerciabilidad, calidad aceptable, idoneidad para el propósito o idoneidad para el resultado divulgado), o cualquier otra derecho o remedio, bajo cualquier legislación o implícito en estos Términos de servicio por cualquier legislación (Garantías legales) se excluye por la presente. Cuando TRAK PHYSIO sea responsable bajo cualquier Garantía legal, y cualquier legislación evite o prohíba las disposiciones de un contrato que excluyan o modifiquen la aplicación, el ejercicio o la responsabilidad en virtud de dichas Garantías legales, la responsabilidad de TRAK PHYSIO por cualquier incumplimiento de dichas Garantías legales será limitada , a opción de TRAK PHYSIO, a uno o más de los siguientes: - si el incumplimiento se refiere a mercancías:la reposición de los bienes o el suministro de bienes equivalentes; la reparación de dichos bienes; el costo de reemplazar los bienes o de adquirir bienes equivalentes; o el costo de reparar los bienes; y - si el incumplimiento se relaciona con los servicios: el suministro de los servicios nuevamente o el costo de que se presten nuevamente los servicios. Usted reconoce y acepta que la confianza de TRAK PHYSIO en esta limitación de responsabilidad es justa y razonable en todas las circunstancias.Usted reconoce y acepta que la confianza de TRAK PHYSIO en esta limitación de responsabilidad es justa y razonable en todas las circunstancias.Usted reconoce y acepta que la confianza de TRAK PHYSIO en esta limitación de responsabilidad es justa y razonable en todas las circunstancias.
            <br />2. En la medida máxima permitida por la ley, TRAK PHYSIO no será responsable de ninguna pérdida (incluyendo pérdidas y daños directos e indirectos), cualquiera que sea la causa (incluso a través de nuestra negligencia), sufrida o incurrida por usted que surja de o en conexión con: - su acceso o uso del Servicio, cualquier Contenido (incluidos los materiales de TRAK PHYSIO, el contenido publicado por el usuario y los programas de ejercicios) o cualquier sitio vinculado; - cualquier decisión o acción tomada por usted basándose en cualquier Contenido (incluidos los materiales de TRAK PHYSIO y el contenido publicado por el usuario); - cualquier error o defecto en el Servicio; o - cualquier contravención por parte de cualquier otro usuario de las leyes aplicables.
            <br />3. Sin perjuicio de este artículo 10, si TRAK PHYSIO es responsable de los daños sufridos por usted, ya sea por contrato, agravio o por cualquier teoría legal, TRAK PHYSIO será responsable únicamente por los daños directos sufridos por usted hasta un monto que no exceda el de sus pagos a TRAK PHYSIO. por el 125% de los últimos 12 meses de Servicio antes del evento que causó el daño o £ 5000, lo que sea mayor.
            <br />4. Daño directo significará únicamente:
            <br /> - Daño directo a la propiedad física
            <br /> - Costo directo de obtener cualquier servicio de reemplazo para los Servicios o gastado para garantizar que el desempeño de TRAK PHYSIO se ajuste a estos Términos de servicio, en cada caso, durante el período - Hasta el fecha de cualquier rescisión del Acuerdo por su parte; o - Hasta la fecha de la primera fecha de vencimiento de cualquier período durante el cual se le proporcionaron los Servicios, lo que ocurra primero. - Costos y gastos desperdiciados en los que haya incurrido al determinar la causa y el alcance de cualquier daño incluido en estos Términos de servicio.
            <br />5. Su derecho a reclamar daños y perjuicios contra TRAK PHYSIO, ya sea por contrato, agravio o sobre cualquier teoría legal, depende de que informe a TRAK PHYSIO de inmediato tan pronto como tenga conocimiento de cualquier hecho o asunto que dé lugar a dicha reclamación y, en cualquier caso, dentro de las tres semanas. de tomar conocimiento de tales hechos y asuntos. 6. Nada en esta cláusula operará para excluir o limitar la responsabilidad de cualquiera de las partes: - por muerte o lesiones personales causadas por la negligencia de esa parte; - por fraude o tergiversación fraudulenta; o - por cualquier otra pérdida o daño que no esté válidamente excluido o limitado por ley.
            <br /><br /><br />10 - Información sobre el servicio<br /><br /><br />
            <br />1. No garantizamos ni representamos la precisión, integridad o idoneidad para su uso previsto de cualquier información (incluido, sin limitación, cualquier Contenido) en el Servicio. Usted es responsable del uso de dicha información y debe realizar sus propias consultas para verificar si la información es precisa, completa y adecuada para su uso previsto.
            <br />2. Todos los ejercicios disponibles en el Servicio son solo demostraciones. Usted reconoce que los proveedores de atención médica son responsables de garantizar que cualquier ejercicio y programa de ejercicio creado para un paciente sea apropiado para ese paciente.
            <br />3. TRAK PHYSIO no respalda ni recomienda ninguna información en la Plataforma o disponible a través del Servicio. Toda la información contenida en la Plataforma y a través del Servicio es solo para uso personal y no puede venderse, redistribuirse ni utilizarse para ningún propósito comercial.
            <br />4. Si es un paciente, siempre existe la posibilidad de sufrir lesiones físicas y al participar en cualquier ejercicio o programa de ejercicios. Si siente malestar o dolor, debe detener de inmediato la actividad que le causa tal malestar o dolor y comunicarse con su proveedor de atención médica o una ambulancia en caso de una emergencia médica. Al usar el Servicio, usted declara que ha informado completamente a su proveedor de atención médica sobre su historial médico y condición existente y ha recibido su consentimiento para participar (y continuar participando) en los programas y ejercicios disponibles para usted en el Servicio.
            <br />5. El Servicio puede contener de vez en cuando enlaces a sitios de Internet mantenidos por terceros. Dichos enlaces se proporcionarán para su conveniencia y no están bajo el control de TRAK PHYSIO. TRAK PHYSIO no es responsable del contenido (incluida la precisión, integridad o idoneidad para su uso previsto) de cualquier sitio vinculado o de cualquier vínculo contenido en un sitio vinculado. TRAK PHYSIO no respalda ninguna información en los sitios vinculados ni en ninguna organización, producto o servicio asociado.
            <br />6. A solicitud del proveedor de atención médica y con el consentimiento del paciente, transferiremos los registros de un paciente al nuevo proveedor de atención médica del paciente que utiliza el Servicio. Una vez que se produce una transferencia, el proveedor de atención médica que realiza la transferencia no podrá acceder a los registros del paciente. Es responsabilidad del proveedor de atención médica que realiza la transferencia asegurarse de que mantiene sus registros relacionados con el paciente de acuerdo con la ley.
            <br /><br /><br />11 - Garantías e indemnizaciones<br /><br /><br />
            <br />1. TRAK PHYSIO no garantiza:
            <br />- que el Servicio estará disponible para usted en todo momento y sin interrupciones, fallos o alteraciones;
            <br />- que el Servicio será efectivo o el uso del Servicio conducirá a ciertos resultados;
            <br /> - que la información proporcionada a través del Servicio sea precisa, actualizada y completa.
            <br />2. TRAK PHYSIO no es responsable (y renuncia expresamente a toda responsabilidad ante usted): - la compra y / o el correcto funcionamiento de su infraestructura; - pérdida, daño, inexactitud y / o falta de integridad de cualquier Contenido; - errores de transmisión, mal funcionamiento o falta de disponibilidad de cualquier computadora, datos o instalaciones de telecomunicaciones, incluido Internet; - cualquier uso no autorizado o intento de uso del Servicio; - hacer copias de seguridad de cualquier contenido; o - la gestión, incluida la comprobación de la configuración, el uso del Servicio y la forma en que se utilizan los resultados del Servicio.
            <br />3. TRAK PHYSIO puede proporcionar interfaces de programación de aplicaciones para permitir la integración del Servicio con otros servicios y plataformas. TRAK PHYSIO no es responsable (y renuncia expresamente a toda responsabilidad ante usted) por otros servicios y plataformas con los que el Servicio se integra o que se integran con el Servicio.
            <br />4. Garantiza que no utilizará el Servicio y / o la Plataforma de manera que:  infrinja los derechos de TRAK PHYSIO o de terceros, incluidos, entre otros, los Derechos de propiedad intelectual o los derechos en relación con la protección de la privacidad; sea contraria a cualquier legislación o normativa vigente o sea contraria a cualquier disposición de estos Términos de servicio.
            <br />5. Usted acepta indemnizar a TRAK PHYSIO por todos los costos, reclamaciones, daños y gastos en los que TRAK PHYSIO incurra como resultado de: cualquier reclamación de un tercero basada en cualquier infracción o presunta infracción de los derechos de propiedad intelectual de dicha parte;  cualquier reclamo de un tercero basado en la violación de la privacidad o el uso indebido o la divulgación de datos personales o el incumplimiento de cualquier ley relacionada con los datos o registros, incluidas, entre otras, sus obligaciones con respecto a la privacidad de sus pacientes según lo establecido en el artículo 6 y cualquier reclamo de un tercero con respecto a cualquier lesión personal o daño a la propiedad física sufrido por ellos, en la medida en que el mismo surja de cualquier acto u omisión ilícito o negligente por su parte en el curso de su uso de la Plataforma o recibir el Servicio o hacer uso del Servicio para proporcionar servicios a otros.
            <br /><br /><br />12 - Varios<br /><br /><br />
            <br />1. TRAK PHYSIO puede ceder o subcontratar derechos y obligaciones que surjan de estos Términos de servicio o del Acuerdo a terceros y se lo notificará. No se le permite ceder o pretender ceder a terceros ningún derecho derivado de la Cuenta sin el consentimiento previo por escrito de TRAK PHYSIO, que TRAK PHYSIO puede otorgar o rechazar a su exclusivo criterio.
            <br />2. Si TRAK PHYSIO renuncia, total o parcialmente, a cualquier derecho disponible para nosotros bajo estos Términos de servicio en cualquier ocasión, esto no significa que esos derechos serán automáticamente renunciados en cualquier otra ocasión.
            <br />3. Si alguna disposición de estos Términos de servicio se considera inválida, inaplicable o ilegal por cualquier motivo, debe leerse para darle el mayor efecto posible, o si no es capaz de tener ningún efecto en absoluto. , debe ser separado de este Acuerdo, en cuyo caso, el resto de estos Términos de servicio continuará sin embargo en plena vigencia.
            <br />4. Estos Términos de servicio y el uso del Servicio se rigen por las leyes de España.
            <br />5. En la medida en que las normas legales nacionales o internacionales no prescriban lo contrario como obligatorio, cualquier disputa que surja o esté relacionada con los acuerdos celebrados con arreglo a estos Términos de servicio, o que surjan de ellos, se someterá únicamente a los tribunales de España, que tendrá jurisdicción exclusiva con respecto a cualquier asunto planteado en virtud de estos Términos de servicio.
        </p>
	</div>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="./popup.js"></script>
</div>

    );
}






export default PopUp;